trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      py27:
        python.version: '2.7'
        onnx_ml: 0
        onnx_debug: 0
      py36:
        python.version: '3.6'
        onnx_ml: 0
        onnx_debug: 0
      py37:
        python.version: '3.7'
        onnx_ml: 0
        onnx_debug: 0
      py37-ml:
        python.version: '3.7'
        onnx_ml: 1
        onnx_debug: 0
      py37-ml-debug:
        python.version: '3.7'
        onnx_ml: 1
        onnx_debug: 1
    maxParallel: 5

  steps:
  - script: sudo install -d -m 0777 /home/vsts/.conda/envs
    displayName: Fix Conda permissions

  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: 'py$(python.version)'
      packageSpecs: 'python=$(python.version) protobuf'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install numpy
      git submodule update --init --recursive
      export ONNX_ML=${onnx_ml}
      export DEBUG=${onnx_debug}
      export ONNX_BUILD_TESTS=1
      export ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI
      export CMAKE_ARGS="-DONNX_WERROR=ON -DONNXIFI_DUMMY_BACKEND=ON -DONNX_USE_LITE_PROTO=ON"
      python setup.py --quiet install
    displayName: 'Install ONNX and dependencies'


  - script: |
      # lint python code
      pip install --quiet flake8
      flake8
      if [ $? -ne 0 ]; then
        echo "Flake8 returned failures"
        exit 1
      fi

      # check line endings to be UNIX
      python -m pip install --quiet -U dos2unix
      find . -type f -regextype posix-extended -regex '.*\.(py|cpp|md|h|cc|proto|proto3|in)' | xargs dos2unix --quiet
      git status
      git diff --exit-code
      
      # check auto-gen files up-to-date
      python onnx/defs/gen_doc.py
      python onnx/gen_proto.py -l
      python onnx/gen_proto.py -l --ml
      python onnx/backend/test/stat_coverage.py
      backend-test-tools generate-data
      git status
      git diff --exit-code      

      # Do not hardcode onnx's namespace in the c++ source code, so that
      # other libraries who statically link with onnx can hide onnx symbols
      # in a private namespace.
      ! grep -R --include='*.cc' --include='*.h' 'namespace onnx' .
      ! grep -R --include='*.cc' --include='*.h' 'onnx::' .

      # onnx python api tests
      pip install --quiet pytest nbval
      pytest
      if [ $? -ne 0 ]; then
        echo "pytest failed"
        exit 1
      fi

      # onnx c++ API tests
      # do not use find -exec here, it would ignore the segement fault of gtest.
      ./.setuptools-cmake-build/onnx_gtests
      ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node

    displayName: 'Run ONNX tests'
